# Generated by Django 4.2.7 on 2024-02-04 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userpage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_href', models.CharField(max_length=20)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
