# Generated by Django 4.2.7 on 2024-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_href',
            field=models.ImageField(upload_to=''),
        ),
    ]
